spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # mydb 부분은 도커 실행 시 설정한 MYSQL_DATABASE 이름과 일치해야 합니다.
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD} # 도커 실행 시 설정한 MYSQL_ROOT_PASSWORD
  jpa:
    hibernate:
      ddl-auto: create # 엔티티에 맞춰 테이블 자동 생성/수정
    show-sql: true     # 실행되는 SQL 쿼리를 로그로 출력
    properties:
      hibernate:
        format_sql: true # SQL 로그를 예쁘게 한 줄씩 정렬
logging.level:
  org.hibernate.SQL: debug
  # 스프링 부트 3.x / Hibernate 6 기준 파라미터 로그 확인
  org.hibernate.orm.jdbc.bind: trace;